module.exports = {
  extends: [
    'bgr',
  ],
  rules: {
    'ember/local-modules': 'error',
    'ember/no-jquery': 'error',
    'ember/no-observers': 'error',
    'ember/order-in-components': ['error', {
      order: [
        'service',
        ['property', 'unknown'],
        'empty-method',
        'single-line-function',
        'multi-line-function',
        'observer',
        'init',
        'didReceiveAttrs',
        'willRender',
        'willInsertElement',
        'didInsertElement',
        'didRender',
        'didUpdateAttrs',
        'willUpdate',
        'didUpdate',
        'willDestroyElement',
        'willClearRender',
        'didDestroyElement',
        'actions',
        'method',
      ],
    }],
    'ember/order-in-controllers': ['error', {
      order: [
        'controller',
        'service',
        'query-params',
        'inherited-property',
        ['property', 'unknown'],
        'init',
        'single-line-function',
        'multi-line-function',
        'observer',
        'actions',
        ['method', 'empty-method'],
      ],
    }],
    'ember/order-in-models': ['error', {
      order: [
        'attribute',
        'relationship',
        'single-line-function',
        'multi-line-function',
      ],
    }],
    'ember/order-in-routes': ['error', {
      order: [
        'service',
        'inherited-property',
        ['property', 'unknown'],
        'init',
        'single-line-function',
        'multi-line-function',
        'beforeModel',
        'model',
        'afterModel',
        'serialize',
        'redirect',
        'activate',
        'setupController',
        'renderTemplate',
        'resetController',
        'deactivate',
        'actions',
        ['method', 'empty-method'],
      ],
    }],
  },
};
